gems:
  - octopress-genesis-theme
  - octopress-debugger
  - octopress-codefence

url: http://jroesch.github.io/
name: Higher Minded Types
author: Jared Roesch
sass:
  sass_dir: _sass
  style: compressed
